---
clone:
  depth: 1
kind: pipeline
name: el9 amd64 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh el9 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh el9 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh el9 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- el9 amd64 build
kind: pipeline
name: el9 sign
platform:
  os: linux
pull: always
steps:
- commands:
  - /usr/local/bin/sign zerotier-builds redhat el9 amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/dnf-builder
  name: sign build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - /usr/local/bin/sign zerotier-releases redhat el9 amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/dnf-builder
  name: sign release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
kind: pipeline
name: jammy amd64 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy ubuntu amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh jammy ubuntu amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh jammy ubuntu amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh jammy ubuntu amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- jammy amd64 build
kind: pipeline
name: jammy sign
platform:
  os: linux
pull: always
steps:
- commands:
  - /usr/local/bin/sign zerotier-builds ubuntu jammy amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: sign build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - /usr/local/bin/sign zerotier-releases ubuntu jammy amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/apt-builder
  name: sign release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- el9 sign
kind: pipeline
name: el9 amd64 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh el9 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh el9 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- jammy sign
kind: pipeline
name: jammy amd64 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh jammy ubuntu amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh jammy ubuntu amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
